import { Fragment, useState, type ReactNode } from 'react';
import type {Category,Summary} from './budget-service';
import {categoryTotals} from './finance-reporting';
import {money} from './service';
export function BudgetRows({b,draft,editable,save,editor}:{b:Summary;draft:boolean;editable:boolean;save:(p:Record<string,unknown>)=>void;editor:(c:Category)=>ReactNode}){
 const [editing,setEditing]=useState<string|null>(null);const total=categoryTotals(b.categories);
 return <table className="finance-table"><caption className="sr-only">{draft?'Plan spending by category':'Category balances'}</caption><thead><tr><th>Category</th><th>{draft?'Allocation':'Budget'}</th>{draft?<th>Forecast</th>:<><th>Requested</th><th>Committed</th><th>Spent</th><th>Available</th></>}<th>Actions</th></tr></thead><tbody>{b.categories.map(c=><Fragment key={c.id}><tr className={c.available<0?'exception-row':''}>
 <td data-label="Category">{draft?<input form={'category-'+c.id} name="name" aria-label={`${c.name} category name`} defaultValue={c.name} required maxLength={100}/>:<strong>{c.name}</strong>}{!c.active&&<span className="finance-badge">Archived</span>}{c.restricted>0&&<small>{money(c.restricted)} restricted funding</small>}</td>
 <td data-label={draft?'Allocation':'Budget'}>{draft?<input form={'category-'+c.id} name="allocation" aria-label={`${c.name} allocation`} defaultValue={c.allocation} type="number" min="0" step="0.01" required/>:<>{money(c.funded)}{c.forecast!==null&&<small>Forecast {money(c.forecast)}</small>}</>}</td>
 {draft?<td data-label="Forecast"><input form={'category-'+c.id} name="forecast" aria-label={`${c.name} forecast`} defaultValue={c.forecast??''} type="number" min="0" step="0.01" placeholder="Optional"/></td>:<><td data-label="Requested">{money(c.requested)}</td><td data-label="Committed">{money(c.committed)}</td><td data-label="Spent">{money(c.spent)}</td><td data-label="Available" className={c.available<0?'negative':''}>{money(c.available)}</td></>}
 <td data-label="Actions">{draft&&<form id={'category-'+c.id} onSubmit={e=>{e.preventDefault();save({...c,...Object.fromEntries(new FormData(e.currentTarget))});}}><button>Save category</button></form>}{editable&&<button aria-expanded={editing===c.id} onClick={()=>setEditing(editing===c.id?null:c.id)}>{draft?'More options':'Edit'}<span className="sr-only"> {c.name}</span></button>}</td></tr>{editing===c.id&&<tr className="editor-row"><td colSpan={draft?4:7}>{editor(c)}</td></tr>}</Fragment>)}</tbody>{!draft&&<tfoot><tr><th>Category totals</th><td data-label="Budget">{money(total.funded)}</td><td data-label="Requested">{money(total.requested)}</td><td data-label="Committed">{money(total.committed)}</td><td data-label="Spent">{money(total.spent)}</td><td data-label="Available">{money(total.available)}</td><td/></tr></tfoot>}</table>;
}
