import { useState, type ReactNode } from 'react';
import type { Budget, Summary } from './budget-service';
import { money, when } from './service';
import { activityText, spendingMonths } from './finance-reporting';
export function FinancialOverview({b}: {b:Summary}) {
 return <section className="finance-overview" aria-label="Season financial summary"><div className="available-hero"><span>Available funding</span><strong>{money(b.available)}</strong><small>After requests, commitments and net spending</small></div><dl className="overview-numbers">{[['Spent',b.spent],['Committed',b.committed],['Requested',b.requested],['Unallocated',b.unallocated]].map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{money(Number(v))}</dd></div>)}</dl><p className="funding-caption">Received income <strong>{money(b.received)}</strong><span>Expected income · planning only <strong>{money(b.expected)}</strong></span></p></section>;
}
export function CategoryChart({b,category=''}:{b:Summary;category?:string}) {
 const cats=b.categories.filter(c=>c.active&&(!category||c.id===category));
 return <section className="panel analytics-panel" aria-label="Category budget chart"><h2>Where the budget stands</h2><p className="chart-legend"><span className="spent-key">Spent</span><span className="committed-key">Committed</span><span className="requested-key">Requested</span><span className="remaining-key">Remaining</span></p>
 {!cats.length&&<p>No active categories to show yet.</p>}
 {cats.map(c=>{const parts=[Math.max(0,c.spent),c.committed,c.requested,Math.max(0,c.available)];const scale=Math.max(c.funded,parts.reduce((a,b)=>a+b,0),1);return <div className="category-chart-row" key={c.id}><div><strong>{c.name}</strong><span className={c.available<0?'negative':''}>{c.available<0?`${money(-c.available)} over budget`:`${money(c.available)} available`}</span></div><div className="category-track" role="img" tabIndex={0} aria-label={`${c.name}: budget ${money(c.funded)}, spent ${money(c.spent)}, committed ${money(c.committed)}, requested ${money(c.requested)}, available ${money(c.available)}`}>{parts.map((amount,i)=><span key={i} className={['spent-segment','committed-segment','requested-segment','remaining-segment'][i]} style={{width:`${amount/scale*100}%`}}/>)}{c.funded>0&&<i style={{left:`${Math.min(100,c.funded/scale*100)}%`}}/>}</div><small>Spent {money(c.spent)} · Committed {money(c.committed)} · Requested {money(c.requested)}</small><small>Budget {money(c.funded)}{c.restricted>0&&` · includes ${money(c.restricted)} restricted funding`}{c.funded===0&&' · no funding assigned'}{c.spent<0&&` · ${money(-c.spent)} net credit`}</small></div>})}
 <details className="budget-help"><summary>Read this chart</summary><p>Each row shows its own funded budget. The marker is the budget limit. Spent is already reduced by credits; negative net spending is labeled separately. Requested and committed purchases are counted once, in their current state.</p></details></section>;
}
export function SpendingChart({budget,category=''}:{budget:Budget;category?:string}) {
 const {months,missing,outside}=spendingMonths(budget,category);const max=Math.max(1,...months.map(m=>Math.abs(m.amount)));
 return <section className="panel analytics-panel" aria-label="Monthly operational spending"><h2>Spending over time</h2><p>Monthly net spending through today · school-submitted POs and manual expenses, minus credits.</p>
 {!months.length?<p>No dated spending recorded yet.</p>:<div className="monthly-chart">{months.map(m=><div className="month-row" key={m.month}><span>{new Date(m.month+'-01T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'})}</span><div className="month-track" role="img" aria-label={`${m.month}: ${money(m.amount)}`}><span className={m.amount<0?'credit-bar':'spending-bar'} style={{width:`${Math.abs(m.amount)/max*50}%`,left:m.amount<0?`${50-Math.abs(m.amount)/max*50}%`:'50%'}}/></div><strong>{money(m.amount)}</strong></div>)}</div>}
 <small>Only months with dated records are shown. Requests and commitments are excluded; this is operational spending, not bank settlement.</small>
 {missing>0&&<p role="status">{missing} record(s) lack a verified spending date and are not plotted.</p>}{outside>0&&<p>{outside} future-dated record(s) are excluded until their date.</p>}</section>;
}
export function FundingChart({b}:{b:Summary}) {const max=Math.max(1,b.starting_funds,b.received,b.expected);return <section className="panel analytics-panel" aria-label="Funding sources"><h2>Funding the season</h2>{[['Starting funds',b.starting_funds],['Received income',b.received],['Expected · not received',b.expected]].map(([name,value],i)=><div className="funding-row" key={String(name)}><div><span>{name}</span><strong>{money(Number(value))}</strong></div><div className="funding-track"><span className={i===2?'expected-bar':'actual-bar'} style={{width:`${Number(value)/max*100}%`}}/></div></div>)}<p>Actual funding <strong>{money(b.actual_funding)}</strong> · expected income is planning only.</p>{b.restricted>0&&<small>{money(b.restricted)} of received income is restricted to designated categories.</small>}</section>}
export function Analytics({budget,reports=false,children}:{budget:Budget;reports?:boolean;children?:ReactNode}) {const [category,setCategory]=useState('');const b=budget.summary;if(!b)return null;return <><FinancialOverview b={b}/>{children}{reports&&<label className="season-picker">Chart category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All active categories</option>{b.categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>Filters category and spending charts. Funding totals remain season-wide.</small></label>}<CategoryChart b={b} category={reports?category:""}/><div className="analytics-grid"><SpendingChart budget={budget} category={reports?category:""}/><FundingChart b={b}/></div></>}
export function RecentActivity({budget}:{budget:Budget}) {const events=budget.history.map(h=>({h,text:activityText(h,budget)})).filter(e=>e.text).slice(0,6);return <section className="panel"><h2>Recent Finance activity</h2>{!events.length?<p>No financial activity yet.</p>:<ul className="finance-activity">{events.map(({h,text})=><li key={h.id}><strong>{text}</strong><small>{h.actor_name} · {when(h.created_at)}</small></li>)}</ul>}</section>}
